### PR TITLE
Rollback the version of minimize to resolve issue with parsing html beyond a small amount

### PR DESCRIPTION
**Pull request by nlisgo**
I have found that the tests break if we increase the size of the index.html test fixtures

### CODE REVIEW

**Comment by nlisgo** [comment]
There seems to be an issue with minimize beyond version 1.2.0 that prevents it from being able to handle anything but a very small amount of html.

**Comment by lewisnyman** [comment]
Ah nice, ok. I'll look at this when I have time

**Comment by jonathanepollack** [comment]
If this is in response to #20, you need to talk to the [minimize guys](https://github.com/Moveo/minimize).

**Comment by nlisgo** [comment]
This is not in response to #20 but I do acknowledge that this is an issue with minimize and I'd love to help them resolve it if I get time but until minimize resolve it then the additional test that I supply as part of this pull request is breaking. This is resolved by ensuring that you don't use minimize beyond version 1.2.0

**Comment by jonathanepollack** [comment]
Can you change `minimize` version to `v1.3.2` and see if everything passes. If so, I'll merge.

**Comment by nlisgo** [comment]
I've done that and it appears to pass.

**Comment by jonathanepollack** [comment]
Many thanks!

**Pull request merged**
